/*******************************************************************************
* This file	was	generated by Phoenix Configuration Wizard.
* 2013-08-24
* Andy He
*******************************************************************************/
#include <os.h>
#include <dsp_dd_interface.h>
/******************************************************************************/
/******************************************************************************/
/* TCB list. */
void *os_tsk_tcb_list[NB_SUPPORT_MAX_TASK_NUM +	1];

/* VECT2TCB	list. */
void *os_vect2tcb_list[256];

/* POOLCB list.	*/
void *os_mem_msgpool_list[NB_POOL_TOTAL_NUM];

/* It should store the nmi process function	entry address */
unsigned int os_debug_nmi_pc = 0xFFFFFFFF;

/* Swap hook */
void Osp_Swap_Hook(u16 swap_to_taskid);
/******************************************************************************/
/******************************************************************************/
// Define the system error handler
OS_BOOLEAN os_error_handler(OS_ERRORCODE err,OS_ERROROPTION	extra, void	*error_msgptr,OS_TASKID	tmpid,OS_BOOLEAN user_called)
{
	u16	error_code,extra_para,pid;

	error_code = (u16)(err&(0x0000ffff));
	extra_para = (u16)(extra&(0x0000ffff));
	pid	= tmpid;

	(void)error_code;
	(void)extra_para;
	(void)pid;
	(void)user_called;
	(void)error_msgptr;

   if(0x80000000 ==	(err & 0x80000000))
   {
	  for (;;)
	  {
		 asm(" nop");
	  }
   }
   return (OS_TRUE);
}

// Fill the system configuration including hooks
const struct OS_CFG_CONFIG os_cfg_info_sys = {
	os_error_handler,/*OS_BOOLEAN UsrErrorFunction(OS_ERRORCODE	error_code,
											OS_ERROROPTION error_opt,
											void *error_msgptr,
											OS_TASKID TSK_Current_Task_ID
											OS_BOOLEAN user_called);*/
	NB_SUPPORT_MAX_TASK_NUM,/*tid you can used :[1..50]	*/
	NB_POOL_TOTAL_NUM,		/*poolid you can used :[0..4] */
	0,						/*rsv16*/
	Osp_Swap_Hook,			/*void (*swap_hook)(OS_TASKID tid);*/
	NULLPTR,				/*void (*send_hook)(union OS_MESSAGE const *msg);*/
	NULLPTR,				/*void (*receive_hook)(union OS_MESSAGE	const *msg);*/
	NULLPTR,				/*void (*alloc_hook)(OS_POOLID poolid, union OS_MESSAGE	const *msg);*/
	NULLPTR,				/*void (*free_hook)(OS_POOLID poolid, union	OS_MESSAGE const *msg);*/
	NULLPTR,				/*void (*create_process_hook)(OS_TASKID	tid);*/
	NULLPTR,				/*void (*create_pool_hook)(OS_POOLID poolid);*/
};

//extern s32 t_dspip_ipcom_initd(void);
//extern int dspip_set_data_buf_poolid(int poolid);

/*s32 iplite_stack_init(void)
{
	s32 ret = 0;
    ret = dspip_set_data_buf_poolid((int)NB_POOLID_IPLITE);
    //Ret = dspip_conf_data_buf_pool(((sizeof(g_u16IpliteBlockConf)/2)/sizeof(unsigned short)), &(g_u16IpliteBlockConf[0]));
    //Ret = dspip_set_iplited_taskid(NB_TASKID_DD_DSPIP_IPLITED);
    ret = t_dspip_ipcom_initd();
	if(ret != OSP_OK)
		return ret;
	else
		return OSP_OK;
}*/

/*********************************End Of File *********************************/
