/*******************************************************************************
* This file	was	generated by Phoenix Configuration Wizard.
* 2013-08-24
* Andy He
*******************************************************************************/
#include <os.h>
#include <dsp_dd_interface.h>
//#include <dd_dspeth_config.h>
//extern s32 iplite_stack_init(void);
/******************************************************************************/
/******************************************************************************/
// List	the	taskID
OS_TASKID const	t_dsp_check_io_ID =	60;
OS_TASKID const	t_dsp_send_ID =	61;

OS_TASKID const t_dsp_appBackground_ID = 62;

// List	the	task entry
//extern OS_TASK(t_dsp_check_io);
//extern OS_TASK(t_dsp_send);

extern OS_TASK(appBackground);

extern void os_smartdsp_init();

// List	the	pool buffer
u8 g_u8_Pool0Buffer[98512 +	8];
u8 g_u8_Pool1Buffer[512000 + 8];
u8 g_u8_Pool2Buffer[524288];
u8 g_u8_Pool3Buffer[32768 +	8];
//u8 g_u8_Pool4Buffer[5120000 + 8]; 

#pragma	align g_u8_Pool0Buffer 8
#pragma	align g_u8_Pool1Buffer 8
#pragma	align g_u8_Pool2Buffer 256
#pragma	align g_u8_Pool3Buffer 8
//#pragma	align g_u8_Pool4Buffer 8

// Configure the pool database
OS_POOL_DB g_struOsPoolDB[]	=
{
	{(u32)NB_POOLID_SYS,(u32)g_u8_Pool0Buffer,(u32)98512, {(u32)128, (u32)512, (u32)1024, (u32)2048, (u32)4096,	(u32)5120, (u32)7168, (u32)10240}},
	{(u32)NB_POOLID_DD,(u32)g_u8_Pool1Buffer,(u32)512000, {(u32)16, (u32)32,	(u32)128, (u32)512,	(u32)1024, (u32)2048, (u32)3072, (u32)8192}},	
	{(u32)NB_POOLID_PL,(u32)g_u8_Pool3Buffer,(u32)32768, {(u32)32, (u32)64,	(u32)128, (u32)256,	(u32)512, (u32)1024, (u32)2048,	(u32)5192}},
	/* 65528 is the possible biggest value(8 bytes alignment), this is for 65024 bytes read request from debugKit */ 	
	//{(u32)NB_POOLID_IPLITE,(u32)g_u8_Pool4Buffer,(u32)5120000, {(u32)256,	(u32)1024, (u32)5120,	(u32)10240, (u32)20480, (u32)30768,	(u32)51200, (u32)65528}},
	{(u32)NB_POOLID_SHARE,(u32)g_u8_Pool2Buffer,(u32)524288, {(u32)224,	(u32)480, (u32)736,	(u32)992, (u32)1504, (u32)2016,	(u32)3040, (u32)10208}}		
};

// Create tasks.
void os_create_tasks(void)
{
	os_create_idle(
		os_default_idle,
		0x0, /*pdata*/
		512	/*in sizeof(C64_STACK) 8bit*/
		);

	
	os_create_task(OS_TSK_PRITASK, /*task type*/
		appBackground,	/*task entry function*/
		0x0, /*pdata*/
		t_dsp_appBackground_ID, /*task id*/
		4096, /*in sizeof(C64_STACK) 8bit*/
		24,	/*priority*/
		NULLVECTOR); /*interrupt pin*/
#if 0	
	os_create_task(OS_TSK_PRITASK, /*task type*/
		t_dsp_check_io,	/*task entry function*/
		0x0, /*pdata*/
		t_dsp_check_io_ID, /*task id*/
		4096, /*in sizeof(C64_STACK) 8bit*/
		24,	/*priority*/
		NULLVECTOR); /*interrupt pin*/

	os_create_task(OS_TSK_PRITASK, /*task type*/
		t_dsp_send, /*task	entry function*/
		0x0, /*pdata*/
		t_dsp_send_ID, /*task id*/
		4096, /*in sizeof(C64_STACK) 8bit*/
		20,	/*priority*/
		NULLVECTOR); /*interrupt pin*/
#endif

}

// Create system pool.
void os_create_system_pool(void)
{
	(void) os_create_sys_message_pool((OS_MEMADDR *)g_struOsPoolDB[NB_POOLID_SYS].pool_addr,
									  (OS_POOLSIZE)g_struOsPoolDB[NB_POOLID_SYS].pool_size,
									  (OS_MSGSIZE const *)&g_struOsPoolDB[NB_POOLID_SYS].sizes_sel[0]);
}

// Create dd and app pools.
void os_create_pools(void)
{
	(OS_POOLID)	os_create_message_pool((OS_POOLID)NB_POOLID_DD,
									   (OS_MEMADDR *)g_struOsPoolDB[NB_POOLID_DD].pool_addr,
									   (OS_POOLSIZE)g_struOsPoolDB[NB_POOLID_DD].pool_size,
									   (OS_MSGSIZE	const *)&g_struOsPoolDB[NB_POOLID_DD].sizes_sel[0]);

	(OS_POOLID)	os_create_message_pool((OS_POOLID)NB_POOLID_PL,
									   (OS_MEMADDR *)g_struOsPoolDB[NB_POOLID_PL].pool_addr,
									   (OS_POOLSIZE)g_struOsPoolDB[NB_POOLID_PL].pool_size,
									   (OS_MSGSIZE	const *)&g_struOsPoolDB[NB_POOLID_PL].sizes_sel[0]);	

	/*(OS_POOLID)	os_create_message_pool((OS_POOLID)NB_POOLID_IPLITE,
									   (OS_MEMADDR *)g_struOsPoolDB[NB_POOLID_IPLITE].pool_addr,
									   (OS_POOLSIZE)g_struOsPoolDB[NB_POOLID_IPLITE].pool_size,
									   (OS_MSGSIZE	const *)&g_struOsPoolDB[NB_POOLID_IPLITE].sizes_sel[0]);*/	
}

// Os start handler1. Interrupt was disabled.
void os_start_handler1(void)
{
	/*OSP_STATUS Ret;
	
	Ret = fdd_dspbsp_hw_init();
    if (OSP_OK != Ret)
    {
        asm(" DEBUG");
    } */	
}

extern volatile int g_int_disable_counter;

// Os start handler1. Interrupt was enabled.
void os_start_handler2(void)
{
	/*OSP_STATUS Ret;
	
    (void)fdd_dspbsp_init();

#ifndef ETHERNET_INIT_ONLY
    (void)fdd_dspdma_init();

    Ret = fdd_dspicc_init(&g_struOsPoolDB[NB_POOLID_SHARE]);  
    if (OSP_OK != Ret)
    {
        asm(" DEBUG");
    } 

    (void)fdd_dspbsp_csm_init();
    
    Ret = fdd_dspdecp_init();
    if (OSP_OK != Ret)
    {
        asm(" DEBUG");
    }

	Ret = fdd_dspcpri_init();
    if (OSP_OK != Ret)
    {
        asm(" DEBUG");
    }
#endif
    
//#ifdef USE_IPLITE_STACK
	Ret = iplite_stack_init();
//#else
	//Ret = fdd_dspeth_init();
//#endif
    if (OSP_OK != Ret)
    {
        asm(" DEBUG");
    }
	
    /* waiting for core sync */ 
    //(void)fdd_dspbsp_init_hook_end();*/
	
	os_smartdsp_init();
	
	/* enable interrupt */
	g_int_disable_counter = 0;
}

void fdd_excep_return_func()
{
	
}

void fdd_excep_handler(u32 exp_index,u32 pc,u32 sp,u32 exp_flag)
{
	
}

void Osp_Swap_Hook(u16 swap_to_taskid)
{
	
}

/*********************************End Of File *********************************/
